apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ca-montreal-sealed-secret.yaml
- ca-montreal-bmc-secret.yaml

generators:
 - ca-montreal.yaml

 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml