apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ca-montreal-sealed-secret.yaml
- ca-montreal-bmc-secret.yaml

generators:
 - ca-montreal.yaml

 - siteConfig-54338184-be14-4e1c-9782-78278cc8dfed.yaml