apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ca-montreal-sealed-secret.yaml
- ca-montreal-bmc-secret.yaml

generators:
 - ca-montreal.yaml

 - siteConfig-54338184-be14-4e1c-9782-78278cc8dfed.yamlsiteConfig-2837e1dc-82c4-44bc-ae6e-6b74ca4c865a.yaml
 - siteConfig-798ab06f-c175-4d21-8ddf-e7a7af25b1ad.yaml
 - siteConfig-ca-montreal.yaml
 - siteConfig-ca-montreal.yaml