apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: ca-montreal
  namespace: ca-montreal
  labels: {}
spec:
  pullSecretRef:
    name: assisted-deployment-pull-secret
  clusterImageSetNameRef: openshift-v4.11.9
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFS0S+jf5OW7CDuwuJO46IpeunNc19oyXlRQwR6tBx67EPXAt3LxB/BMbyr8+MLMIErzaIUSvG70yk34cB4jbXrs8cbwSdxGPro3ZZqu9qT8+ILhEXtok6uUBG8OKlhIqrAm6Iq3hH1Kbgwj/72B9eaKIpNHzvrZSM/UNAYZzNvENuBGeWuO1kfxnhWmzp+eh+8vTPcYdLzJKv+BOQBxz6T8SI5By0TfvAvVS2xMmhMRMs1TBDLUBgzZgd06X0ghSaOimz4aVbmqI4WwClIy8ZiXhL/j1IkSF97qNo26yb/yYnyk+BqqrsOQIEQQcfzY+skpHQ1JiPjPVYHsujhgctFgwCR0/KKw2QcqOK67est5gDW3vaf/zIDhRnPdT2IhJQTQNEepRjKfHF2EgGIMSU4TosJ5ygx+q0oZ5ITcFHSiIK3aoOt2QXZPY+Dtork5zYbE2M3PLrgRrT1VW1eTH6v5GYjUDq95mwcKYBirSvd3QuUbrGjFQuxfCZlceUui0=
    adetalhouet@joatmon.localdomain
  sshPrivateKeySecretRef:
    name: ""
  clusters:
  - apiVIP: ""
    ingressVIP: ""
    apiVIPs: []
    ingressVIPs: []
    clusterName: ca-montreal
    holdInstallation: false
    additionalNTPSources: []
    nodes:
    - bmcAddress: redfish-virtualmedia+http://192.168.1.170:8000/redfish/v1/Systems/181d3e23-d417-40a9-88cf-1e01d7fb75fe
      bootMACAddress: "02:04:00:00:01:03"
      rootDeviceHints: {}
      cpuset: ""
      nodeNetwork:
        config: {}
        interfaces: []
      nodeLabels: {}
      hostName: ca-montreal-node1
      bmcCredentialsName:
        name: bmh-secret
      bootMode: ""
      userData: {}
      installerArgs: ""
      ignitionConfigOverride: ""
      role: master
      crTemplates: {}
      biosConfigRef:
        filePath: ""
      diskPartition: []
      ironicInspect: ""
    machineNetwork:
    - cidr: 192.168.123.0/24
    serviceNetwork:
    - 172.30.0.0/16
    clusterLabels:
      common: "true"
      sites: ca-montreal
    networkType: OVNKubernetes
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    ignitionConfigOverride: ""
    diskEncryption:
      type: ""
      tang: []
    extraManifestPath: ""
    biosConfigRef:
      filePath: ""
    extraManifests:
      filter: null
    cpuPartitioningMode: ""
    extramanifestonly: false
    nummasters: 0
    numworkers: 0
    clustertype: ""
    crTemplates: {}
    mergeDefaultMachineConfigs: false
  baseDomain: adetalhouet.ca
  crTemplates: {}
  biosConfigRef:
    filePath: ""
