---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: ca-montreal
  namespace: ca-montreal
spec:
  clusterName: ca-montreal
  baseDomain: adetalhouet.ca
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: ca-montreal
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          agentclusterinstalls.extensions.hive.openshift.io/location: Montreal
  pullSecretRef:
    name: assisted-deployment-pull-secret