---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno-ztp-cluster
  namespace: sno-ztp-cluster
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sno-ztp-cluster
  namespace: sno-ztp-cluster
spec:
  clusterName: sno-ztp-cluster
  clusterNamespace: sno-ztp-cluster
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  observabilityController:
      enabled: true
  workManager:
      enabled: true