# This CR verifies the installation/upgrade of the Sriov Fec Operator
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: web-terminal.web-terminal
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
status:
  components:
    refs:
    - kind: Subscription
      namespace: web-terminal
      conditions:
      - type: CatalogSourcesUnhealthy
        status: "False"
    - kind: InstallPlan
      namespace: web-terminal
      conditions:
      - type: Installed
        status: "True"
    - kind: ClusterServiceVersion
      namespace: web-terminal
      conditions:
      - type: Succeeded
        status: "True"
        reason: InstallSucceeded
